services:
  torch:
    image: pytorch/pytorch:2.4.1-cuda11.8-cudnn9-devel
    container_name: pytorch-gpu-dev
    restart: unless-stopped
    ports:
      - 8889:8889
    volumes:
      - ./workspaces:/root/workspaces:rw
    command: >
      /bin/sh -c "python3 -m pip install jupyter && jupyter lab --ip=0.0.0.0 --port 8889 --no-browser --allow-root --notebook-dir=/root/workspaces"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    tty: true